# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-07 22:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Demands',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('demand_reference', models.CharField(max_length=20)),
                ('client_name', models.CharField(max_length=250)),
                ('phone', models.IntegerField()),
                ('email', models.CharField(max_length=250)),
                ('followUp_blog', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Properties',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('property_reference', models.CharField(max_length=20)),
                ('title', models.CharField(max_length=250)),
                ('photolink', models.CharField(max_length=250)),
                ('price', models.FloatField()),
                ('description', models.CharField(max_length=1000)),
            ],
        ),
    ]
