# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-12 23:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listing', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='properties',
            name='photolink',
            field=models.FileField(upload_to=''),
        ),
    ]
